backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
site_url: https://optimistic-poitras-148d9a.netlify.com
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    editor:
      preview: false
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "select", multiple: true, options: ["kerala", "india", "world", "business", "movie", "tech", "job", "sports", "health", "auto", "she", "travel", "homestyle", "index"]}
      - {label: "Audio File", name: "speech", widget: "file", required: false}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Youtube Video Id", name: "youtubeId", widget: "string", required: false}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
